"""Generate the Audits client's TypeScript contracts from FastAPI OpenAPI schemas."""

import argparse
from pathlib import Path

from maintainer_api.main import app

MODELS = [
    "CreateAuditRequest",
    "PlanDecisionRequest",
    "RepositoryAuditResult",
    "AuditSnapshot",
]


def render(schema: dict) -> str:
    """Translate the JSON Schema subset emitted by the audit API."""
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(render(item) for item in schema["anyOf"])
    if "enum" in schema:
        import json

        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{render(schema.get('items', {}))}>"
    if kind == "object":
        if "properties" not in schema:
            extra = schema.get("additionalProperties", {})
            return f"Record<string, {render(extra) if isinstance(extra, dict) else 'unknown'}>"
        required = schema.get("required", [])
        return (
            "{\n"
            + "\n".join(
                f"  {key}{'' if key in required else '?'}: {render(value)};"
                for key, value in schema["properties"].items()
            )
            + "\n}"
        )
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def main() -> None:
    """Write or verify generated contracts without downloading a code generator."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schemas = app.openapi()["components"]["schemas"]
    content = (
        "// Generated by scripts/export_audit_types.py. Do not edit.\n\n"
        + "\n\n".join(
            f"export type {name} = {render(schemas[name])};" for name in MODELS
        )
        + "\n"
    )
    path = Path(__file__).resolve().parents[1] / "apps/web/app/lib/audit-types.ts"
    if args.check:
        if path.read_text() != content:
            raise SystemExit("Audit types are stale; run scripts/export_audit_types.py")
    else:
        path.write_text(content)


if __name__ == "__main__":
    main()
